ARG BASE_IMAGE=cps_docker
FROM ${BASE_IMAGE}

RUN pip3 install ds4drv

RUN apt update && \
    DEBIAN_FRONTEND=nonineractive \
    apt install -y \
        ros-noetic-joy \
        python3-catkin-tools
                