ARG BASE_IMAGE=cps_docker
FROM ${BASE_IMAGE}

RUN pip3 install ds4drv pyquaternion scipy

RUN apt update && \
    DEBIAN_FRONTEND=nonineractive \
    apt install -y \
        ros-noetic-joy \
        ros-noetic-openzen-sensor \
        python3-catkin-tools 